// Supabase Edge Function: fetch-daily-news
// Description: Cron-triggered function that fetches external raw news every 2 hours
//              (at 00:00, 02:00, 04:00, 06:00, 08:00, 10:00, 12:00, 14:00, 16:00, 18:00, 20:00, 22:00 UTC),
//              curates it via Groq Llama-3.3-70b-versatile, and populates the news_briefs table.

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.38.4";

const GROQ_API_KEY = Deno.env.get("GROQ_API_KEY");
const SUPABASE_URL = Deno.env.get("DB_URL");
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("DB_SERVICE_KEY");

const NEWS_API_KEY = Deno.env.get("NEWS_API_KEY");
const GNEWS_API_KEY = Deno.env.get("GNEWS_API_KEY");
const GUARDIAN_KEY = Deno.env.get("GUARDIAN_KEY");
const NYT_API_KEY = Deno.env.get("NYT_API_KEY");

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  // Handle CORS
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const keys = [
      Deno.env.get("GROQ_API_KEY"),
      Deno.env.get("GROQ_API_KEY_2"),
      Deno.env.get("GROQ_API_KEY_3"),
      Deno.env.get("GROQ_API_KEY_4"),
      Deno.env.get("GROQ_API_KEY_5"),
    ].filter((k): k is string => typeof k === "string" && k.trim() !== "");

    if (keys.length === 0 || !SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
      throw new Error("Missing system environment variables (At least one GROQ_API_KEY, DB_URL, and DB_SERVICE_KEY is required).");
    }

    const debugLogs: string[] = [];
    debugLogs.push("Request started.");

    // Check optional keys
    if (!GUARDIAN_KEY) {
      debugLogs.push("Guardian API Key is missing. Guardian layer will be skipped silently.");
    }
    if (!NYT_API_KEY) {
      debugLogs.push("NYT API Key is missing. NYT layer will be skipped silently.");
    }

    console.log("Initializing Supabase Admin Client...");
    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

    // Fetch news categories dynamically from DB with fallback
    const activeCategories = await fetchActiveCategories(supabase, debugLogs);

    console.log("Fetching raw articles...");
    const rawArticles = await fetchRawArticles(activeCategories, debugLogs);
    console.log(`Fetched ${rawArticles.length} raw articles to curate.`);
    debugLogs.push(`Fetched ${rawArticles.length} raw articles successfully.`);

    console.log("Screening articles via Groq...");
    const screenedArticles = await screenTitles(rawArticles, keys, debugLogs);
    console.log(`Screened articles: ${screenedArticles.length} remaining out of ${rawArticles.length}.`);
    debugLogs.push(`Screened articles: ${screenedArticles.length} remaining out of ${rawArticles.length}.`);

    console.log("Invoking Groq model for AI curation...");
    const briefings = await curateWithGroq(screenedArticles, activeCategories, debugLogs);
    console.log(`Groq generated ${briefings.length} curated news briefings.`);
    debugLogs.push(`Groq generated ${briefings.length} briefs.`);

    // Post-curation deduplication step
    const seenBriefingHeadlines = new Set<string>();
    const deduplicatedBriefings: CuratedBrief[] = [];
    let removedCount = 0;
    for (const b of briefings) {
      if (!b.headline) {
        deduplicatedBriefings.push(b);
        continue;
      }
      const normalizedHeadline = b.headline.trim().toLowerCase().replace(/[^a-z0-9]/g, "");
      if (seenBriefingHeadlines.has(normalizedHeadline)) {
        removedCount++;
      } else {
        seenBriefingHeadlines.add(normalizedHeadline);
        deduplicatedBriefings.push(b);
      }
    }
    console.log(`Deduplication removed ${removedCount} duplicate briefings.`);
    debugLogs.push(`Deduplication removed ${removedCount} duplicate briefings.`);

    // Filter out any brief where headline is empty or null/undefined, or summary is empty or null/undefined. Never insert blank articles.
    const validBriefings = deduplicatedBriefings.filter((b) => {
      const hasHeadline = b.headline && b.headline.trim() !== "";
      const hasSummary = b.summary && b.summary.trim() !== "";
      return hasHeadline && hasSummary;
    });

    console.log(`Groq generated ${briefings.length} curated news briefings. Valid briefs: ${validBriefings.length}`);
    debugLogs.push(`Groq generated ${briefings.length} briefs. Valid: ${validBriefings.length}`);

    if (validBriefings.length === 0) {
      return new Response(JSON.stringify({
        success: false,
        message: "No valid briefings generated by Groq (all were blank or missing headlines/summaries).",
        logs: debugLogs
      }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 200,
      });
    }

    const todayStr = new Date().toISOString().split("T")[0];
    const nowTimestamp = new Date().toISOString();

    // Purge all active news_briefs for today so we never accumulate stale/mock data
    console.log("Purging existing news_briefs for today before inserting fresh ones...");
    const { error: purgeError } = await supabase
      .from("news_briefs")
      .delete()
      .eq("fetched_date", todayStr)
      .eq("is_active", true);
    if (purgeError) {
      console.error("Failed to purge old briefs:", purgeError);
    } else {
      console.log("Successfully purged old briefs for today.");
    }

    console.log("Writing curated briefings to news_briefs table...");

    // Prepare inserts
    const inserts = validBriefings.map((b, index) => {
      const pubAt = b.published_at?.trim();
      const isNone = !pubAt || pubAt === "" || pubAt.toLowerCase() === "none";
      return {
        category: b.category,
        source_name: b.source_name,
        original_title: b.original_title,
        headline: b.headline,
        key_fact: b.key_fact,
        summary: b.summary,
        published_at: isNone ? null : pubAt,
        fetched_date: todayStr,
        fetched_at: nowTimestamp,
        display_order: index + 1,
        is_active: true,
        image_url: b.image_url || null,
      };
    });

    const { error: insertError } = await supabase.from("news_briefs").insert(inserts);

    if (insertError) {
      throw insertError;
    }

    return new Response(JSON.stringify({ success: true, count: inserts.length, data: inserts }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
      status: 200,
    });
  } catch (error) {
    console.error("Error in Edge Function execution:", error.message);
    return new Response(JSON.stringify({ success: false, error: error.message }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
      status: 500,
    });
  }
});

async function fetchActiveCategories(supabase: any, debugLogs: string[]): Promise<any[]> {
  try {
    debugLogs.push("Fetching active categories from news_categories table...");
    const { data, error } = await supabase
      .from("news_categories")
      .select("slug, label, display_order, keywords")
      .eq("is_active", true)
      .order("display_order", { ascending: true });

    if (error) {
      throw error;
    }

    if (data && data.length > 0) {
      debugLogs.push(`Fetched ${data.length} active categories successfully from Supabase.`);
      return data;
    }
  } catch (e) {
    console.error("Failed to fetch news_categories, falling back to defaults:", e);
    debugLogs.push(`news_categories query failed: ${e.message || e}. Using hardcoded default categories.`);
  }

  // Hardcoded fallback list
  return [
    { slug: "world", label: "World", display_order: 1, keywords: ["global diplomacy", "international relations", "wars", "treaties", "UN", "NATO", "climate accords", "humanitarian", "foreign policy"] },
    { slug: "tech", label: "Tech", display_order: 2, keywords: ["gadgets", "software", "hardware", "Apple", "Google", "Microsoft", "Samsung", "startups", "cybersecurity", "robotics", "semiconductors"] },
    { slug: "ai", label: "AI", display_order: 3, keywords: ["artificial intelligence", "machine learning", "LLMs", "OpenAI", "Anthropic", "Gemini", "ChatGPT", "neural networks", "AI regulation", "AI tools"] },
    { slug: "science", label: "Science", display_order: 4, keywords: ["space", "NASA", "ISRO", "physics", "biology", "medicine", "research", "discoveries", "quantum", "environment", "climate science"] },
    { slug: "india", label: "India", display_order: 5, keywords: ["Indian government", "ISRO", "Indian economy", "Indian startups", "Modi", "Indian sports", "infrastructure", "Indian tech"] },
    { slug: "movies", label: "Movies", display_order: 6, keywords: ["film releases", "box office", "trailers", "directors", "OTT", "Netflix", "Amazon Prime", "Disney+", "awards", "sequels"] },
    { slug: "entertainment", label: "Entertainment", display_order: 7, keywords: ["gaming", "esports", "YouTube", "streaming", "music industry", "anime", "comics", "Marvel", "DC", "celebrity projects"] },
    { slug: "social_media", label: "Social Media", display_order: 8, keywords: ["Instagram", "Twitter", "X", "TikTok", "Meta", "YouTube policy", "viral trends", "platform updates", "creator economy"] },
    { slug: "sports", label: "Sports", display_order: 9, keywords: ["cricket", "football", "F1", "Olympics", "NBA", "tennis", "IPL", "FIFA", "athlete records", "championships"] },
    { slug: "politics", label: "Politics", display_order: 10, keywords: ["elections", "government policy", "parliament", "laws", "international politics", "diplomatic decisions", "official statements"] },
    { slug: "economy", label: "Economy", display_order: 11, keywords: ["stock market", "GDP", "inflation", "RBI", "Federal Reserve", "trade", "corporate earnings", "startup funding", "crypto"] }
  ];
}

/**
 * Fetches raw articles from a News API or uses a fallback curated list
 */
async function fetchRawArticles(activeCategories: any[], debugLogs: string[]) {
  // Execute all 3 layers in parallel
  const [rssArticles, guardianArticles, nytArticles] = await Promise.all([
    fetchRSSLayer(debugLogs).catch((e) => {
      console.error("[Layer 1 RSS] Failed:", e);
      debugLogs.push(`Layer 1 (RSS) failed: ${e.message || e}`);
      return [];
    }),
    fetchGuardianLayer(debugLogs).catch((e) => {
      console.error("[Layer 2 Guardian] Failed:", e);
      debugLogs.push(`Layer 2 (Guardian) failed: ${e.message || e}`);
      return [];
    }),
    fetchNYTLayer(debugLogs).catch((e) => {
      console.error("[Layer 3 NYT] Failed:", e);
      debugLogs.push(`Layer 3 (NYT) failed: ${e.message || e}`);
      return [];
    })
  ]);

  // Log total count per source layer
  console.log(`[Source Layers Fetch Counts]`);
  console.log(`- Layer 1 (RSS): ${rssArticles.length} raw articles`);
  console.log(`- Layer 2 (Guardian): ${guardianArticles.length} raw articles`);
  console.log(`- Layer 3 (NYT): ${nytArticles.length} raw articles`);

  debugLogs.push(`[Source Layer Stats] RSS: ${rssArticles.length}, Guardian: ${guardianArticles.length}, NYT: ${nytArticles.length}`);

  // Merge all results
  const flatArticles = [...rssArticles, ...guardianArticles, ...nytArticles];

  // 1. Calculate source counts before any filtering
  const totalRSS = rssArticles.length;
  const totalGuardian = guardianArticles.length;
  const totalNYT = nytArticles.length;
  const totalBeforeDedup = flatArticles.length;

  // 2. Deduplicate by normalized title
  const seenTitles = new Set<string>();
  const dedupedArticles: any[] = [];
  for (const a of flatArticles) {
    const normalizedTitle = a.title.trim().toLowerCase().replace(/[^a-z0-9]/g, "");
    if (normalizedTitle && !seenTitles.has(normalizedTitle)) {
      seenTitles.add(normalizedTitle);
      dedupedArticles.push(a);
    }
  }
  const totalAfterDedup = dedupedArticles.length;

  // 3. Filter by 4 hours for logging
  const now = new Date();
  const cutoffTime4h = now.getTime() - (4 * 60 * 60 * 1000); // 4 hours in milliseconds
  const articles4h = dedupedArticles.filter((a: any) => {
    if (!a.publishedAt) return false;
    const pubTime = new Date(a.publishedAt).getTime();
    return pubTime >= cutoffTime4h;
  });
  const totalAfter4h = articles4h.length;

  // 4. Relax the age filter from 4 hours to 48 hours (48 hours in milliseconds) for actual curation
  const cutoffTime48h = now.getTime() - (48 * 60 * 60 * 1000);
  const freshArticles = dedupedArticles.filter((a: any) => {
    if (!a.publishedAt) return false;
    const pubTime = new Date(a.publishedAt).getTime();
    return pubTime >= cutoffTime48h;
  });
  const totalAfter48h = freshArticles.length;

  // Print exact logs requested by the user
  console.log(`Total from RSS feeds combined: ${totalRSS}`);
  console.log(`Total from Guardian API: ${totalGuardian}`);
  console.log(`Total from NYT API: ${totalNYT}`);
  console.log(`Total before deduplication: ${totalBeforeDedup}`);
  console.log(`Total after deduplication: ${totalAfterDedup}`);
  console.log(`Total after 4-hour age filter: ${totalAfter4h}`);
  console.log(`Total after 48-hour age filter: ${totalAfter48h}`);

  debugLogs.push(`Total from RSS feeds combined: ${totalRSS}`);
  debugLogs.push(`Total from Guardian API: ${totalGuardian}`);
  debugLogs.push(`Total from NYT API: ${totalNYT}`);
  debugLogs.push(`Total before deduplication: ${totalBeforeDedup}`);
  debugLogs.push(`Total after deduplication: ${totalAfterDedup}`);
  debugLogs.push(`Total after 4-hour age filter: ${totalAfter4h}`);
  debugLogs.push(`Total after 48-hour age filter: ${totalAfter48h}`);

  // Use the 48-hour relaxed articles for final curation
  const finalArticles = freshArticles.slice(0, 96);
  debugLogs.push(`Sending top ${finalArticles.length} unique articles (within 48 hours) to Groq curation.`);

  if (finalArticles.length === 0) {
    debugLogs.push("All source layers returned empty. No articles to curate.");
    return [];
  }

  return finalArticles;
}

/**
 * Layer 1 — RSS Feeds fetched via rss2json
 */
async function fetchRSSLayer(debugLogs: string[]): Promise<any[]> {
  const rssFeeds = [
    { name: "BBC World", url: "http://feeds.bbci.co.uk/news/world/rss.xml" },
    { name: "BBC Tech", url: "http://feeds.bbci.co.uk/news/technology/rss.xml" },
    { name: "BBC Science", url: "http://feeds.bbci.co.uk/news/science_and_environment/rss.xml" },
    { name: "BBC Entertainment", url: "http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml" },
    { name: "BBC Sport", url: "http://feeds.bbci.co.uk/news/sport/rss.xml" },
    { name: "Reuters Top News", url: "https://feeds.reuters.com/reuters/topNews" },
    { name: "Reuters Tech", url: "https://feeds.reuters.com/reuters/technologyNews" },
    { name: "Reuters Business", url: "https://feeds.reuters.com/reuters/businessNews" },
    { name: "TechCrunch", url: "https://techcrunch.com/feed/" },
    { name: "TechCrunch AI", url: "https://techcrunch.com/category/artificial-intelligence/feed/" },
    { name: "NASA Breaking News", url: "https://www.nasa.gov/rss/dyn/breaking_news.rss" },
    { name: "ESPN Top Headlines", url: "https://www.espn.com/espn/rss/news" },
    { name: "Deadline Hollywood", url: "https://deadline.com/feed/" },
    { name: "The Hindu National", url: "https://www.thehindu.com/news/national/feeder/default.rss" },
    { name: "The Hindu Science", url: "https://www.thehindu.com/sci-tech/science/feeder/default.rss" },
    { name: "NDTV Top Stories", url: "https://feeds.feedburner.com/ndtvnews-top-stories" },
    { name: "Wired", url: "https://www.wired.com/feed/rss" },
    { name: "MIT Tech Review", url: "https://www.technologyreview.com/feed/" },
    { name: "Reuters Science", url: "https://feeds.reuters.com/reuters/scienceNews" },
    { name: "Reuters Entertainment", url: "https://feeds.reuters.com/reuters/entertainment" },
    { name: "CNN World", url: "https://rss.cnn.com/rss/edition.rss" },
    { name: "BBC Business", url: "https://feeds.bbci.co.uk/news/business/rss.xml" },
    { name: "BBC Health", url: "https://feeds.bbci.co.uk/news/health/rss.xml" },
    { name: "The Verge", url: "https://www.theverge.com/rss/index.xml" },
    { name: "Gizmodo", url: "https://gizmodo.com/rss" },
    { name: "Engadget", url: "https://www.engadget.com/rss.xml" },
    { name: "Ars Technica", url: "https://feeds.arstechnica.com/arstechnica/index" },
    { name: "Variety", url: "https://variety.com/feed/" },
    { name: "Space.com", url: "https://www.space.com/feeds/all" },
    { name: "Economic Times India", url: "https://economictimes.indiatimes.com/rssfeedstopstories.cms" },
    { name: "Times of India", url: "https://timesofindia.indiatimes.com/rssfeeds/296589292.cms" }
  ];

  console.log(`[Layer 1 RSS] Fetching ${rssFeeds.length} feeds directly in parallel...`);

  const results = await Promise.all(
    rssFeeds.map(async (feed) => {
      try {
        const res = await fetch(feed.url);
        if (!res.ok) {
          console.error(`[Layer 1 RSS] Direct fetch for ${feed.name} failed with HTTP status ${res.status}: ${res.statusText}`);
          debugLogs.push(`${feed.name} HTTP error: ${res.status}`);
          return [];
        }
        const xmlText = await res.text();

        // Custom simple XML string parser
        const items: any[] = [];
        const itemRegex = /<item>([\s\S]*?)<\/item>/g;
        let match;

        const cleanCDATA = (str: string) => {
          return str.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, "$1").trim();
        };

        const getTagValue = (xml: string, tag: string): string => {
          const regex = new RegExp(`<${tag}[^>]*>([\\s\\S]*?)<\/${tag}>`, "i");
          const m = xml.match(regex);
          return m ? cleanCDATA(m[1]) : "";
        };

        const getAttributeValue = (xml: string, tag: string, attr: string): string => {
          const regex = new RegExp(`<${tag}[^>]*?${attr}=["']([^"']+)["']`, "i");
          const m = xml.match(regex);
          return m ? m[1] : "";
        };

        let count = 0;
        while ((match = itemRegex.exec(xmlText)) !== null && count < 8) {
          const itemXml = match[1];
          const title = getTagValue(itemXml, "title");
          if (!title) continue;

          const description = getTagValue(itemXml, "description");
          const pubDate = getTagValue(itemXml, "pubDate");

          let imageUrl = getAttributeValue(itemXml, "enclosure", "url");
          if (!imageUrl) {
            imageUrl = getAttributeValue(itemXml, "media:content", "url");
          }
          if (!imageUrl) {
            imageUrl = getAttributeValue(itemXml, "media:thumbnail", "url");
          }
          if (!imageUrl) {
            imageUrl = getAttributeValue(itemXml, "content", "url");
          }

          items.push({
            title: title,
            description: description,
            source: feed.name,
            publishedAt: pubDate || new Date().toISOString(),
            imageUrl: imageUrl || ""
          });
          count++;
        }

        return items;
      } catch (e) {
        console.error(`[Layer 1 RSS] Exception fetching ${feed.name}:`, e);
        debugLogs.push(`RSS feed ${feed.name} failed: ${e.message || e}`);
        return [];
      }
    })
  );

  return results.flat();
}

/**
 * Layer 2 — The Guardian API
 */
async function fetchGuardianLayer(debugLogs: string[]): Promise<any[]> {
  if (!GUARDIAN_KEY) {
    debugLogs.push("Guardian API key missing, silently skipping Guardian layer.");
    return [];
  }

  const sections = ["world", "technology", "science", "sport", "film", "business", "politics"];
  console.log(`[Layer 2 Guardian] Fetching ${sections.length} sections in parallel...`);

  const results = await Promise.all(
    sections.map(async (section) => {
      try {
        const url = `https://content.guardianapis.com/search?section=${section}&show-fields=trailText,thumbnail&page-size=8&api-key=${GUARDIAN_KEY}`;
        const res = await fetch(url);
        if (!res.ok) {
          const bodyText = await res.text();
          console.log(`[Layer 2 Guardian] Section ${section} failed with HTTP status ${res.status}. Body (first 200 chars): ${bodyText.substring(0, 200)}`);
          debugLogs.push(`Guardian section ${section} HTTP error: ${res.status}`);
          return [];
        }
        const data = await res.json();

        if (data.response?.status === "ok" && Array.isArray(data.response.results)) {
          return data.response.results.map((item: any) => ({
            title: item.webTitle || "",
            description: item.fields?.trailText || "",
            source: "The Guardian",
            publishedAt: item.webPublicationDate || new Date().toISOString(),
            imageUrl: item.fields?.thumbnail || ""
          }));
        } else {
          const rawString = JSON.stringify(data);
          console.log(`[Layer 2 Guardian] Section ${section} API status check failed. Response body (first 200 chars): ${rawString.substring(0, 200)}`);
          debugLogs.push(`Guardian section ${section} API check failed.`);
        }
        return [];
      } catch (e) {
        console.error(`[Layer 2 Guardian] Exception in section ${section}:`, e);
        debugLogs.push(`Guardian section ${section} failed: ${e.message || e}`);
        return [];
      }
    })
  );

  return results.flat();
}

/**
 * Layer 3 — NYT API
 */
async function fetchNYTLayer(debugLogs: string[]): Promise<any[]> {
  if (!NYT_API_KEY) {
    debugLogs.push("NYT API key missing, silently skipping NYT layer.");
    return [];
  }

  const sections = ["world", "technology", "science", "sports", "movies", "business", "politics"];
  console.log(`[Layer 3 NYT] Fetching ${sections.length} sections in parallel...`);

  const results = await Promise.all(
    sections.map(async (section) => {
      try {
        const url = `https://api.nytimes.com/svc/topstories/v2/${section}.json?api-key=${NYT_API_KEY}`;
        const res = await fetch(url);
        const data = await res.json();

        if (data.status === "OK" && Array.isArray(data.results)) {
          return data.results.map((item: any) => ({
            title: item.title || "",
            description: item.abstract || "",
            source: "New York Times",
            publishedAt: item.published_date || new Date().toISOString(),
            imageUrl: item.multimedia?.[0]?.url || ""
          }));
        }
        return [];
      } catch (e) {
        debugLogs.push(`NYT section ${section} failed: ${e.message || e}`);
        return [];
      }
    })
  );

  return results.flat();
}

interface CuratedBrief {
  category: string;
  source_name: string;
  original_title: string;
  headline: string;
  key_fact: string;
  summary: string;
  published_at?: string;
  image_url?: string;
}

/**
 * Screens article titles using Groq to filter out articles that are not worth curating
 */
async function screenTitles(articles: any[], keys: string[], debugLogs: string[]): Promise<any[]> {
  if (articles.length === 0) {
    return [];
  }
  if (keys.length === 0) {
    console.error("No Groq API keys available in environment for screening.");
    debugLogs.push("No Groq API keys available in environment for screening.");
    return articles;
  }

  // Takes up to 96 articles
  const listToScreen = articles.slice(0, 96);
  const simplified = listToScreen.map((art, index) => ({
    index: index,
    title: art.title || ""
  }));

  const promptText = `You are UTOPIA's Daily AI News Screening Assistant. Your job is to review a list of article titles and select only those that are newsworthy, factual, and suitable for a high-quality, student-focused news briefing.

Screening Rules:
- SELECT articles that are: newsworthy, factual reports of events, scientific discoveries, space missions, tech developments, official policy agreements, economic stats, movie/entertainment releases, or sporting events.
- DO NOT SELECT (FILTER OUT) articles that are:
  - Opinion pieces, editorials, or columns
  - Lifestyle articles, tips, self-help, how-to guides, advice, recipes, or lists (e.g., "5 ways to...", "How to stay healthy...")
  - Social media drama, celebrity gossip, influencer outrage, or platform controversies
  - Crime, shootings, killings, violence, war tragedies, deaths, or highly depressing events
  - Speculative rumors, vague claims, or political blame/attacks
- SKIP words commonly associated with sensationalism or outrage (e.g. blast, outrage, controversy, disgraceful).

Input format: A JSON array of objects with an 'index' and a 'title'.
Output format: You MUST output the result as a strict, valid JSON object matching the following schema, with no markdown code blocks, backticks, or extra text:
{
  "selected_indices": number[]
}

Here are the articles to screen:
${JSON.stringify(simplified, null, 2)}`;

  const url = "https://api.groq.com/openai/v1/chat/completions";
  let currentKeyIndex = 0;
  let success = false;
  let selectedIndices: number[] = [];

  for (let offset = 0; offset < keys.length; offset++) {
    const i = (currentKeyIndex + offset) % keys.length;
    const currentKey = keys[i];
    const maskedKey = currentKey.length > 12
      ? `${currentKey.substring(0, 8)}...${currentKey.substring(currentKey.length - 4)}`
      : "Invalid Key Length";

    console.log(`[Groq Title Screening] Attempting screening with Key ${i + 1}/${keys.length} (${maskedKey})...`);
    debugLogs.push(`Attempting Groq Screening with Key ${i + 1}/${keys.length} (${maskedKey})...`);

    try {
      const response = await fetch(url, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${currentKey}`
        },
        body: JSON.stringify({
          model: "llama-3.3-70b-versatile",
          messages: [
            {
              role: "user",
              content: promptText
            }
          ],
          response_format: {
            type: "json_object"
          }
        })
      });

      console.log(`[Groq Title Screening] HTTP Status: ${response.status} (OK: ${response.ok})`);
      debugLogs.push(`Groq Screening HTTP Status: ${response.status}`);

      if (response.status === 429) {
        console.warn(`[Groq Title Screening] Key ${i + 1} is exhausted (Rate Limited - 429). Rotating...`);
        debugLogs.push(`Screening Key ${i + 1} Rate Limited (429). Rotating...`);
        continue;
      }

      if (!response.ok) {
        const errorText = await response.text();
        console.warn(`[Groq Title Screening] Key ${i + 1} failed with status ${response.status}: ${errorText}. Rotating...`);
        debugLogs.push(`Screening Key ${i + 1} failed with status ${response.status}: ${errorText.substring(0, 150)}`);
        continue;
      }

      const result = await response.json();
      const rawText = result.choices?.[0]?.message?.content;
      if (!rawText) {
        console.warn(`[Groq Title Screening] Key ${i + 1} returned empty content. Rotating...`);
        debugLogs.push(`Screening Key ${i + 1} returned empty content.`);
        continue;
      }

      console.log(`[Groq Title Screening] Screening successful using Key ${i + 1}!`);
      debugLogs.push(`Screening successful using Key ${i + 1}!`);

      let cleanText = rawText.trim();
      if (cleanText.startsWith("```json")) {
        cleanText = cleanText.substring(7);
      } else if (cleanText.startsWith("```")) {
        cleanText = cleanText.substring(3);
      }
      if (cleanText.endsWith("```")) {
        cleanText = cleanText.substring(0, cleanText.length - 3);
      }
      cleanText = cleanText.trim();

      const parsed = JSON.parse(cleanText);
      if (parsed && Array.isArray(parsed.selected_indices)) {
        selectedIndices = parsed.selected_indices;
      }
      success = true;
      break;
    } catch (e) {
      console.error(`[Groq Title Screening] Exception caught with Key ${i + 1}:`, e);
      debugLogs.push(`Screening Key ${i + 1} caught exception: ${e.message || e}`);
    }
  }

  if (!success) {
    console.error("[Groq Title Screening] All available Groq API keys were exhausted or failed for screening.");
    debugLogs.push("All available Groq API keys were exhausted or failed for screening. Returning all articles as fallback.");
    return listToScreen;
  }

  // Filter the original articles array based on selected indices
  const filteredArticles = listToScreen.filter((_, index) => selectedIndices.includes(index));
  console.log(`[Groq Title Screening] Filtered articles from ${listToScreen.length} down to ${filteredArticles.length}`);
  debugLogs.push(`Screening filtered articles from ${listToScreen.length} down to ${filteredArticles.length}`);
  return filteredArticles;
}

/**
 * Curates raw articles into standard structured briefs using Groq Llama-3.3-70b-versatile with automatic key rotation
 */
/**
 * Curates raw articles into standard structured briefs using Gemini 2.0 Flash in a single API call
 */
/**
 * Curates raw articles into standard structured briefs using Groq Llama-3.3-70b-versatile in batches of 10
 */
/**
 * Curates raw articles into standard structured briefs using Groq Llama-3.3-70b-versatile with automatic key rotation
 */
async function curateWithGroq(articles: any[], activeCategories: any[], debugLogs: string[]): Promise<CuratedBrief[]> {
  // Collect all available Groq API keys from environment variables
  const keys = [
    Deno.env.get("GROQ_API_KEY"),
    Deno.env.get("GROQ_API_KEY_2"),
    Deno.env.get("GROQ_API_KEY_3"),
    Deno.env.get("GROQ_API_KEY_4"),
    Deno.env.get("GROQ_API_KEY_5"),
  ].filter((k): k is string => typeof k === "string" && k.trim() !== "");

  if (keys.length === 0) {
    console.error("No Groq API keys available in environment.");
    debugLogs.push("No Groq API keys available in environment.");
    return [];
  }

  // Split into batches of 10 articles each
  const batchSize = 10;
  const batches: any[][] = [];
  for (let i = 0; i < articles.length; i += batchSize) {
    batches.push(articles.slice(i, i + batchSize));
  }

  console.log(`[Curation Engine] Curating ${articles.length} articles in ${batches.length} batches of 10...`);
  debugLogs.push(`Curating ${articles.length} articles in ${batches.length} batches of 10...`);

  const allBriefs: CuratedBrief[] = [];
  let currentKeyIndex = 0;

  for (let b = 0; b < batches.length; b++) {
    const batchArticles = batches[b];
    console.log(`[Curation Engine] Curating Batch ${b + 1}/${batches.length} (${batchArticles.length} articles)...`);
    debugLogs.push(`Curating Batch ${b + 1}/${batches.length}...`);

    if (b > 0) {
      console.log("[Curation Engine] Waiting 3 seconds to prevent rate limiting...");
      await new Promise(r => setTimeout(r, 3000));
    }

    // Strip each article down to only 3 fields before sending to Groq: title, source, description
    const simplifiedArticles = batchArticles.map((art: any) => ({
      title: art.title || "",
      source: art.source || "",
      description: art.description || ""
    }));

    const promptText = `You are UTOPIA's Daily AI News Editor. Your job is to curate, validate, and summarize raw news articles into concise, high-quality, student-focused briefing cards.
              
    Filter Rules (STRICT):
    - SKIP any article about: political attacks, party blame, election drama, protests, misinformation claims, social media outrage, controversies, cartoons/satire
    - SKIP any article where tone is conflict-based, outrage-based, or divisive
    - STRICT SKIP RULE: If an article is a tips list, advice guide, how-to, or lifestyle piece — output should_include: false for it. Do NOT include it even if it relates to science or health. Only include articles reporting a specific event, announcement, decision, discovery, or result that happened on a specific date.
    - INCLUDE politics only for: official policy decisions, signed agreements, diplomatic meetings with concrete outcomes, election results with final numbers
    - INCLUDE india only for: infrastructure, science, economy, space, technology, development projects
    - INCLUDE world only for: international agreements, diplomatic outcomes, global events with clear factual outcomes
    - SKIP if the headline contains words like: blast, outrage, controversy, disgraceful
    - SKIP: any article containing deaths, shootings, killings, violence, or crime in the headline or description
    - CRITICAL: If you do not have enough real articles for a category, output fewer articles for that category. Never invent placeholder articles. Never output articles with 'None' as source, headline, or summary. Only output real articles from the input. It is acceptable to output 0 articles for a category if no relevant articles exist.
    - Summary: concise and direct, maximum 2 sentences, no fluff
    - Enforce category diversity: maximum 4 articles per category in the final output
    - Minimum 6 different categories must be represented in the final output
    - Only include articles that clearly match at least one category's keywords
    
    Classify each article into exactly one of these categories based on the keywords:
    ${activeCategories.map((c: any) => `- '${c.slug}' (${c.label}): keywords — ${c.keywords.join(', ')}`).join('\n')}
    
    Generate 4–5 briefs per category if possible.
    
    For each brief, output:
    1. "category": one of ${activeCategories.map((c: any) => `'${c.slug}'`).join(', ')}.
    2. "source_name": short name of the source (e.g. 'Reuters', 'BBC', 'Bloomberg').
    3. "original_title": the exact original raw headline.
    4. "headline": a rewritten, clean, active headline (maximum 12 words) that states exactly what happened.
    5. "key_fact": a single, bulletproof, highly objective 1-sentence key takeaway starting with a verb or concrete numbers (e.g., 'Over 140 nations agreed to triple clean energy funding').
    6. "summary": a highly readable, scannable, and engaging maximum 2-sentence summary explaining the full context, details, and significance of the story. If the raw input article's description is extremely short, vague, or single-sentence, you MUST use your own extensive pre-trained general knowledge about the event, public figures, or technological breakthrough to elaborate and construct a rich, highly informative, and complete summary. Never output single-phrase or extremely short summaries.

    You MUST output the result as a strict, valid JSON object matching the following TypeScript schema, with no markdown code blocks, backticks, or extra text:
    {
      "briefs": Array<{
        category: string; // must be one of: ${activeCategories.map((c: any) => c.slug).join(', ')}
        source_name: string;
        original_title: string;
        headline: string;
        key_fact: string;
        summary: string;
      }>
    }

    Here are the raw articles to curate:
    ${JSON.stringify(simplifiedArticles, null, 2)}`;

    const url = "https://api.groq.com/openai/v1/chat/completions";

    let batchSuccess = false;
    for (let offset = 0; offset < keys.length; offset++) {
      const i = (currentKeyIndex + offset) % keys.length;
      const currentKey = keys[i];
      const maskedKey = currentKey.length > 12
        ? `${currentKey.substring(0, 8)}...${currentKey.substring(currentKey.length - 4)}`
        : "Invalid Key Length";

      console.log(`[Groq Key Curation] Attempting Batch ${b + 1} with Key ${i + 1}/${keys.length} (${maskedKey})...`);
      debugLogs.push(`Attempting Groq Key ${i + 1}/${keys.length} (${maskedKey})...`);

      try {
        const response = await fetch(url, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${currentKey}`
          },
          body: JSON.stringify({
            model: "llama-3.3-70b-versatile",
            messages: [
              {
                role: "user",
                content: promptText
              }
            ],
            response_format: {
              type: "json_object"
            }
          })
        });

        console.log(`[Groq Key Curation] Batch ${b + 1} Key ${i + 1} HTTP Status: ${response.status} (OK: ${response.ok})`);
        debugLogs.push(`Batch ${b + 1} Key ${i + 1} HTTP Status: ${response.status}`);

        if (response.status === 429) {
          console.warn(`[Groq Key Curation] Key ${i + 1} is exhausted (Rate Limited - 429). Rotating to next key...`);
          debugLogs.push(`Key ${i + 1} Rate Limited (429). Rotating...`);
          continue;
        }

        if (!response.ok) {
          const errorText = await response.text();
          console.warn(`[Groq Key Curation] Key ${i + 1} failed with status ${response.status}: ${errorText}. Rotating...`);
          debugLogs.push(`Key ${i + 1} failed with status ${response.status}: ${errorText.substring(0, 150)}`);
          continue;
        }

        const result = await response.json();
        const rawText = result.choices?.[0]?.message?.content;
        if (!rawText) {
          console.warn(`[Groq Key Curation] Key ${i + 1} returned empty content. Rotating...`);
          debugLogs.push(`Key ${i + 1} returned empty message content.`);
          continue;
        }

        console.log(`[Groq Key Curation] Batch ${b + 1} Curation successful using Key ${i + 1}!`);
        debugLogs.push(`Batch ${b + 1} Curation successful using Key ${i + 1}!`);

        let cleanText = rawText.trim();
        if (cleanText.startsWith("```json")) {
          cleanText = cleanText.substring(7);
        } else if (cleanText.startsWith("```")) {
          cleanText = cleanText.substring(3);
        }
        if (cleanText.endsWith("```")) {
          cleanText = cleanText.substring(0, cleanText.length - 3);
        }
        cleanText = cleanText.trim();

        const parsed = JSON.parse(cleanText);
        if (parsed && Array.isArray(parsed.briefs)) {
          // Re-attach imageUrl and publishedAt by matching on original_title
          const mappedBriefs = parsed.briefs.map((b: any) => {
            const matchingArticle = batchArticles.find((art: any) => art.title && art.title.trim() === b.original_title?.trim());
            return {
              ...b,
              image_url: matchingArticle?.imageUrl || null,
              published_at: matchingArticle?.publishedAt || new Date().toISOString()
            };
          });
          allBriefs.push(...mappedBriefs);
        }

        currentKeyIndex = i;
        batchSuccess = true;
        break;

      } catch (e) {
        console.error(`[Groq Key Curation] Exception caught with Key ${i + 1} in batch ${b + 1}:`, e);
        debugLogs.push(`Key ${i + 1} caught exception in batch ${b + 1}: ${e.message || e}`);
        console.log("[Groq Key Curation] Rotating to next key...");
      }
    }

    if (!batchSuccess) {
      console.error(`[Groq Key Curation] All available Groq API keys were exhausted or failed for batch ${b + 1}.`);
      debugLogs.push(`All available Groq API keys were exhausted or failed for batch ${b + 1}.`);
    }
  }

  return allBriefs;
}
